services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./src:/diakosmisi/src
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: diakosmisi1!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
